//Muhammad Khizr Shahid
//2413235



//libraries
#include<stdlib.h>
#include<stdio.h>
#include<math.h>
#include<time.h>
#include<string.h>

//prototypes for the functions used below
void create_code(char **);
void player_guess(char **, int);
int find_score(char **,char **,char **);
void display_winner(int, int, char **);
void display_score(char **);

//main function
int main () {

    //declaration and initialization of variables
    int i, round, found;
    char **secret_code, **score, **guess, choice;
    srand(time(NULL));

    secret_code = (char **)malloc(4*sizeof(char*)); //dynamic memory allocation

        if (secret_code== (char **)NULL) { //error check
            printf("\nFailed to allocate array\n");
            exit(1);
        }

    for(i=0;i<4;i++) {
        secret_code[i]=(char *) malloc(7*sizeof(char)); //dynamic memory allocation

            if (secret_code[i]== (char *)NULL) { //error check for each
                printf("\nFailed to allocate array\n");
                exit(1);
            }
    }



    guess = (char **)malloc(4*sizeof(char*)); //dynamic memory allocation

        if (guess== (char **)NULL) { //error check
            printf("\nFailed to allocate array\n");
            exit(1);
        }

    for(i=0;i<4;i++) {
        guess[i]=(char *) malloc(7*sizeof(char)); //dynamic memory allocation

            if (guess[i]== (char *)NULL) { //error check for each
                printf("\nFailed to allocate array\n");
                exit(1);
            }
    }

    score = (char **)malloc(4*sizeof(char*)); //dynamic memory allocation

        if (score== (char **)NULL) { //error check
            printf("\nFailed to allocate array\n");
            exit(1);
        }

    for(i=0;i<4;i++) {
        score[i]=(char *) malloc(7*sizeof(char)); //dynamic memory allocation

            if (guess[i]== (char *)NULL) { //error check for each
                printf("\nFailed to allocate array\n");
                exit(1);
            }
    }

    do {
        //initialization and declaration of variables
        round = 0;
        found = 0;

        printf("CODEBREAKER IS STARTING!\n"); //starting statement
        create_code(secret_code); //calls the function to create codes(colors) and store them in secret_code array
        printf("Secret code generated!\n"); //informs the user that colors are generated so proceed further now

        do {

            round++; //increments round

            player_guess(guess, round); //calls the function to ask the user to enter the colors he/she has guessed and want to play with
            found = find_score(secret_code, guess, score); //calls the function to compare your guess color with the code color generated by the system and then calculate the score which will be stored in the system or array called score
            display_score(score); //prints the score stored in score array and indicates the user regarding the results about his/her guess whether he/she guessed the correct position and color both or just one of them or none of them

        } while ((round < 8) && (found != 4)); //condition for the loop
                                            // condition for round is 8 because he can play only 8 rounds in one game and condition for found is 4 because he can correctly guess a maximum of 4 colors only

        display_winner(found, round, secret_code); //it finally informs the user whether he has lost or won the game by printing that
                                                    //Also tells the user what was the code actually generated by the system which he guessed along with telling the user after how many rounds he guessed all of them correct


        do { //A do-while loop which keeps the program running after the user has played once in such a way that at the end it asks user what he wants to do next
                //this loop works in such a way that if user wants to play the game again then he can press y and the game will start all over again
                //if the user does not want to play the game again then he can press n and the loop will stop/break and program will stop

            printf("Would you like to play again (Y/N)? ");
            fflush(stdin);
            scanf("%c", &choice); //asks user for giving input

        } while (((choice != 'y') && (choice != 'Y')) && ((choice != 'N') && (choice != 'n'))); //user can enter his preference in block letters or small letters

    } while ((choice != 'n') && (choice != 'N'));

    printf("Bye!");

    free(secret_code); //this frees the arrays
    free(guess);
    free(score);

return 0; //program ends
}

void create_code(char **secret_code) {

    int choice; //declaration of variable

    for(int i=0;i<4;i++) { //user has to choose 4 colors hence a for loop for 4 times for 4 colors
        choice = rand() % 5 + 2; // black 1 and white 0 hence addition of 2 to the mod value so that we get values from 2 till 6 inclusive to which we are assigning colors which user can guess and enter

        if(choice == 2) {
            strcpy(secret_code[i],"red"); //if value received is 2 then red color is copied to the secret code array using copy string function
        }
        else if(choice == 3) {
            strcpy(secret_code[i],"green"); //if value received is 3 then green color is copied to the secret code array using copy string function
        }
        else if(choice==4) {
            strcpy(secret_code[i],"orange"); //if value received is 4 then orange color is copied to the secret code array using copy string function
        }
        else if(choice==5) {
            strcpy(secret_code[i],"blue"); //if value received is 5 then blue color is copied to the secret code array using copy string function
        }
        else {
            strcpy(secret_code[i],"yellow"); //if value received is 6 then yellow color is copied to the secret code array using copy string function
        }
    }
}

void player_guess(char **guess, int round) {

    printf("%d.Enter your Guess:", round); //It asks user to enter the color guess which user will use to play the game
    scanf("%s %s %s %s", guess[0], guess[1], guess[2], guess[3]); //as user is required to enter 4 colors to play the game that's why 4 colors are stored in 4 respective positions in array of string i.e guess

}

int find_score (char **secret_code, char **guess, char **score) {
    int count = 0, i; //initialization and declaration of variables

    for(int i=0;i<4;i++) { //4 colors are to be checked to find the score as user is supposed to enter 4 colors hence a for loop for 4 turns
        if(strcmp(secret_code[i],guess[i])==0) { //if the color assigned to secret code in the create code function by rand mod is same as the color guessed by the user
            strcpy(score[i],"black"); //then the word black is copied to score which indicates that the color guessed is correct with the correct position
            count++; //count variable is incremented after this
        }
        else if(strcmp(secret_code[0],guess[i])==0) { //if the color guessed matches the color stored in  secret code but has a different position from the position where that color is stored then white is copied to score
            strcpy(score[i],"white");                   //which indicates that color guessed by the user is correct but the position is incorrect
        }
        else if(strcmp(secret_code[1],guess[i])==0) { //color guessed is available in that array hence color guessed is correct but position is incorrect hence white copied
            strcpy(score[i],"white");
        }
        else if(strcmp(secret_code[2],guess[i])==0) { //color guessed is available in that array hence color guessed is correct but position is incorrect hence white copied
            strcpy(score[i],"white");
        }
        else if(strcmp(secret_code[3],guess[i])==0) { //color guessed is available in that array hence color guessed is correct but position is incorrect hence white copied
            strcpy(score[i],"white");
        }
        else {
            strcpy(score[i],"_"); //if the color guessed is incorrect and the position guessed is also incorrect then an empty blank is copied to score
        }
    }

    return count; //returns count an integer from this function
}

void display_score(char **score) {

    printf("Your score:"); //prints the 4 option/colors ( black/white/_ ) copied to the score array in previous function by comparing whether user guessed correct color and position both or just one of them or none of them
    for(int i=0;i<4;i++)
    {
        printf(" %s",score[i]);
    }
    printf("\n");

}

void display_winner (int found, int round, char **secret_code) {

        int i; //declaration of variable

        if (found != 4) { //if all 4 colors are not guessed correctly then the following statement is printed to inform user he has lost
            printf("You LOST\n");
        }
        else {
            printf("You win the game!\n"); //if all 4 colors are guessed correctly then user is informed that he/she has won the game
            printf("SECRETCODE ="); //prints the secret code which was generated by system and which was asked by the user to be guessed
            for(i=0;i<4;i++) {
                printf(" %s",secret_code[i]);
            }
            printf("\nYou found it after %d guesses\n", round); //tells the user that after how many rounds he was able to guess all the colors correctly with correct positions
        }

}
